site_name: "brainformr documentation"
nav:
  - 'index.md'
  - Code reference information: 
    - data + dataloader: data.md
    - model attention matrix format: model.md
    - post-hoc analysis: analysis.md
  #- Generating embeddings:
  #- Clustering embeddings:

  - Other applications: 
    - Training on Zhuang lab data:
      - zhuang_abc.md
  - API Reference: reference/

repo_url: https://github.com/alexj-lee/brainformr

plugins:
  - search
  #- with-pdf
  - section-index
  - literate-nav:
       nav_file: SUMMARY.md
  - mkdocstrings:
      handlers:
        python:
          paths: [brainformr]
          options:
            docstring_style: numpy
          rendering:
            show_root_heading: true
            show_root_full_path: true
            show_signature_annotations: true
            show_if_no_docstring: true
            members_order: source
          selection:
            inherited_members: true

  - gen-files:
      scripts:
        - docs_scripts/gen_ref_pages.py
      config:
        skip_paths:
          - brainformr/brainformr/__init__.py
          - brainformr/brainformr/data/loader_polars.py

exclude_docs:
  _version.py


theme:
    name: material
    #logo: "_static/favicon.png"
    features:
        - navigation.sections  # Sections are included in the navigation on the left.
        - toc.integrate  # Table of contents is integrated on the left; does not appear separately on the right.
        - header.autohide  # header disappears as you scroll
        - content.code.copy
    palette:
        # Light mode / dark mode
        # We deliberately don't automatically use `media` to check a user's preferences. We default to light mode as
        # (a) it looks more professional, and (b) is more obvious about the fact that it offers a (dark mode) toggle.
        - scheme: default
          primary: white
          accent: teal
          toggle:
             icon: material/weather-night
             name: Switch to dark mode
        - scheme: slate
          primary: black
          accent: teal
          toggle:
             icon: material/weather-sunny
             name: Switch to light mode
    icon:
        repo: fontawesome/brands/github  # GitHub logo in top right
        logo: fontawesome/solid/brain  # Brain logo in top left

markdown_extensions:
- pymdownx.highlight:
    anchor_linenums: true
    line_spans: __span
    pygments_lang_class: true
- pymdownx.inlinehilite
- pymdownx.snippets
- pymdownx.superfences


